baseURL = "https://tonymwinters.github.io/cheesycloud/"
languageCode = "en-us"
title = "CheesyCloud"
theme = "hyde"

[params]
layoutReverse = true
description = "How much cheese is too much cheese?"
themeColor = "theme-base-0d"
publishDir = "docs"